### ISSUE TITLE
Values don't update with props input

### ISSUE THREAD

**Issue by chrisbyers** [madist/react-ion-slider#5]
The slider seems to only initialize on the first render, not updating as input props are updated and render is re-called.  Example is I initialize the slider to default values on app startup, then load data from a db, and when I set the min, max, from, and to values at the props input to the IonRangeSlider component, it doesn't update (still shows my defaults), although with some debug I can see that the component's render() method is called again with the updated props.  They just don't seem to make it into the internal renderer.

**Comment by CPQM07** [comment]
hi @chrisbyers, i have an other observation.. I read the documentation but didn't find a property to set the input name. How are you setting it?

**Comment by chrisbyers** [comment]
@CPQM07 Sorry, when I titled it "props input", I just meant when setting the props for various features of the slider (min, max, from, and to values).  I'm not sure what "input name" you are speaking of.

**Comment by CPQM07** [comment]
@chrisbyers Okay! no problem, well, I was looking for this react component because I used the jquery version and it works perfect.

The component generates a hidden input text but i don't see how to set the name asociated to the form.... How do you capture the value of the slider?

Thanks a lot! Happy coding!

**Comment by madist** [comment]
hi @chrisbyers , let me check. you mean you need to re render after first initialization ?
